services:
  # PostgreSQL Database for Evolution API
  evolution-postgres:
    image: postgres:15
    container_name: evolution-postgres
    environment:
      POSTGRES_DB: evolution
      POSTGRES_USER: evolution
      POSTGRES_PASSWORD: evolution_secure_2024
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    volumes:
      - evolution_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U evolution"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Evolution API
  evolution-api:
    image: atendai/evolution-api:v2.1.1
    container_name: whatsapp-evolution
    depends_on:
      evolution-postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      # Server Configuration
      - SERVER_TYPE=http
      - SERVER_PORT=8080
      - SERVER_URL=http://localhost:8080
      
      # CORS Configuration
      - CORS_ORIGIN=*
      - CORS_METHODS=POST,GET,PUT,DELETE
      - CORS_CREDENTIALS=true
      
      # Database Configuration (PostgreSQL)
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://evolution:evolution_secure_2024@evolution-postgres:5432/evolution
      - DATABASE_CONNECTION_CLIENT_NAME=evolution_api
      
      # Store Configuration
      - STORE_MESSAGES=true
      - STORE_MESSAGE_UP=true
      - STORE_CONTACTS=true
      - STORE_CHATS=true
      
      # Webhook Configuration (connects to your AI PBX)
      - WEBHOOK_GLOBAL_ENABLED=true
      - WEBHOOK_GLOBAL_URL=http://host.docker.internal:3000/webhook
      - WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS=true
      - WEBHOOK_GLOBAL_IGNORE_JID=false
      
      # Auth Configuration
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=ai-pbx-evolution-key-2024
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
      
      # Log Configuration
      - LOG_LEVEL=ERROR,WARN,INFO
      - LOG_COLOR=true
      - LOG_BAILEYS=error
      
      # Instance Configuration
      - CONFIG_SESSION_PHONE_CLIENT=AI-PBX
      - CONFIG_SESSION_PHONE_NAME=AI PBX Assistant
      
      # QR Code Configuration
      - QRCODE_LIMIT=30
      - QRCODE_COLOR=#198754
      
      # Cleanup Configuration
      - CLEAN_STORE_CLEANING_INTERVAL=7200000
      - CLEAN_STORE_MESSAGE=true
      
    volumes:
      - evolution_instances:/evolution/instances
    restart: unless-stopped

volumes:
  evolution_postgres_data:
  evolution_instances: